In [5]:
import pandas as pd 
import numpy as np 
import extract_dataframe
import clean_tweets_dataframe
#from extract_dataframe import *
#from clean_tweets_dataframe import *

In [2]:
df_twitter = pd.read_json('data/africa_twitter_data.json',lines=True,nrows=5000)
df_twitter.head()

,created_at,id,id_str,full_text,truncated,display_text_range,entities,metadata,source,in_reply_to_status_id,...,retweet_count,favorite_count,favorited,retweeted,lang,extended_entities,possibly_sensitive,quoted_status_id,quoted_status_id_str,quoted_status
0,2022-08-03 20:19:13+00:00,1554924874166149120,1554924874166149120,#Pelosi airplane landed safely in #Taiwan üáπüáº ...,False,"[0, 222]","{'hashtags': [{'text': 'Pelosi', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,0,False,False,en,NaN,NaN,NaN,NaN,NaN
1,2022-08-02 15:24:42+00:00,1554488368347680771,1554488368347680768,Watch the video of the beginning of the Chines...,False,"[0, 250]","{'hashtags': [{'text': 'Pelosi', 'indices': [1...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,...,0,3,False,False,en,"{'media': [{'id': 1554487694776012800, 'id_str...",0.0,NaN,NaN,NaN
2,2022-08-02 15:02:35+00:00,1554482802502127621,1554482802502127616,#Pelosi \n#Taipei \n#taiwan\n#XiJinping \n#Chi...,False,"[0, 71]","{'hashtags': [{'text': 'Pelosi', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,2,False,False,en,"{'media': [{'id': 1554482776140906497, 'id_str...",0.0,NaN,NaN,NaN
3,2022-08-01 13:51:42+00:00,1554102573635932160,1554102573635932160,#HOBIPALOOZA #LaAcademiaExpulsion #WEURO2022 #...,False,"[0, 146]","{'hashtags': [{'text': 'HOBIPALOOZA', 'indices...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,0,False,False,en,"{'media': [{'id': 1554102566010732544, 'id_str...",0.0,NaN,NaN,NaN
4,2022-07-31 20:02:20+00:00,1553833459440910338,1553833459440910336,#Pelosi\n#china\nChina Time ‚úåÔ∏è https://t.co/tE...,False,"[0, 28]","{'hashtags': [{'text': 'Pelosi', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,2,False,False,en,"{'media': [{'id': 1553833456853045256, 'id_str...",0.0,NaN,NaN,NaN

In [3]:
#df_full_text = 
pd.set_option('display.max_colwidth',100)
fulltest_list = list(df_twitter['full_text'].head())
fulltest_list

['#Pelosi airplane landed safely in #Taiwan üáπüáº  \n1) - Both üá®üá≥ &amp;  üá∫üá∏ are playing "win win" on financial markets. 2) - Taiwan may be the future Asian   Cuba  3) - üá∫üá∏ &amp; üá®üá≥ need an Asian #NATO / #5G\nWhat\'s your thoughts?',
 'Watch the video of the beginning of the Chinese bombing of Taiwan during Pelosi visit from here : https://t.co/twah6WU4fZ\nŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄŸÄ\n#Pelosi #„Éû„ÉÑ„Ç≥„ÅÆÁü•„Çâ„Å™„ÅÑ‰∏ñÁïå #Yediiklim #BadDecisionsTrailer1 #LawnBowls #Á•ù_CALL119_MV900‰∏áÂõû #‡∏°‡∏≤‡∏Å‡∏≠‡∏î‡∏Å‡∏±‡∏ô‡∏ô‡∏∞‡∏ã‡∏µ‡∏û‡∏§‡∏Å‡∏©‡πå https://t.co/m4CXfyZRS7',
 '#Pelosi \n#Taipei \n#taiwan\n#XiJinping \n#China \nOn a verge of another war https://t.co/DuqDiSnWcd',
 '#HOBIPALOOZA #LaAcademiaExpulsion #WEURO2022 #jhopeAtLollapalooza #SuzukiPakistan #Fantastico #Taiwan #breastfeeding #Kosovo #BORNPINK  strong ‚úçÔ∏èüíú https://t.co/GtZeNL24rm',
 '#Pelosi\n#china\nChina Time ‚úåÔ∏è https://t.co/tEDjzTlszu']

In [9]:
list(df_twitter['source'].head())

['<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
 '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
 '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
 '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
 '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>']

In [14]:
def find_screen_name_test(self)->list:
    screen_name = []
    for items in self:
        screen_name.append(items['user']['screen_name'])
    return screen_name

In [24]:
from extract_dataframe import TweetDfExtractor

twiiter_sample = TweetDfExtractor(df_twitter)
screenames_t = twiiter_sample.find_screen_name()

TypeError: string indices must be integers, not 'str'

In [26]:
df_twitter_sample = df_twitter['user'].apply(lambda x: x['screen_name'])

list(df_twitter_sample.head())

['DzCritical', 'toopsat', 'NassimaLilEmy', 'd_dhayae', 'Mohamme65404115']

In [27]:
df_twitter_sample = df_twitter['user'].apply(lambda x: x['followers_count'])

list(df_twitter_sample.head())

[318, 764, 64, 60, 39]

In [32]:
df_twitter_sample = df_twitter['user'].apply(lambda x: x['friends_count'])

list(df_twitter_sample.head())

[373, 144, 47, 463, 206]

In [28]:
list(df_twitter['created_at'].head())

[Timestamp('2022-08-03 20:19:13+0000', tz='UTC'),
 Timestamp('2022-08-02 15:24:42+0000', tz='UTC'),
 Timestamp('2022-08-02 15:02:35+0000', tz='UTC'),
 Timestamp('2022-08-01 13:51:42+0000', tz='UTC'),
 Timestamp('2022-07-31 20:02:20+0000', tz='UTC')]

In [29]:
df_twitter_sample = df_twitter['user'].apply(lambda x: x['statuses_count'])

list(df_twitter_sample.head())

[888, 1597, 2293, 44, 1313]

In [31]:
list(df_twitter['possibly_sensitive'].head())

[nan, 0.0, 0.0, 0.0, 0.0]

In [7]:
import json

test_df_twitter = df_twitter.to_json()

with open ('tests/test_df_twitter.json','w',encoding='utf-8') as f:
    json.dump(test_df_twitter,f, ensure_ascii=False, indent=4)

In [28]:
df_twitter['source'].unique()

array(['<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
       '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
       '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
       '<a href="https://www.notice.com.ng/" rel="nofollow">notice.com.ng</a>',
       '<a href="https://ifttt.com" rel="nofollow">IFTTT</a>',
       '<a href="https://www.bobojaytv.com" rel="nofollow">BobojayTV News</a>',
       '<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>',
       '<a href="http://publicize.wp.com/" rel="nofollow">WordPress.com</a>',
       '<a href="https://dlvrit.com/" rel="nofollow">dlvr.it</a>',
       '<a href="http://instagram.com" rel="nofollow">Instagram</a>',
       '<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
       '<a href="https://jokoshq.com" rel="nofollow">Jokoshq</a>',
       '<a href="https://buffer.com" rel="nofollow">Buffer</a>',
       '<a href="https://www.hootsuite.com" rel="nofollow">Hootsuite Inc.</a>',
       '<a href="https://periscope.tv" rel="nofollow">Periscope</a>',
       '<a href="https://nicknackdevelopment.com" rel="nofollow">Albatross for Twitter</a>',
       '<a href="https://www.blog2social.com" rel="nofollow">Blog2Social APP</a>',
       '<a href="http://erased25052531_ogxIxCF7zJ.com" rel="nofollow">erased25052531_ogxIxCF7zJ</a>',
       '<a href="http://erased25047992_VmR4Zfuw1q.com" rel="nofollow">erased25047992_VmR4Zfuw1q</a>',
       '<a href="https://ads.twitter.com" rel="nofollow">Twitter Ads</a>'],
      dtype=object)

In [21]:
df_africa = pd.read_json('data/Economic_Twitter_Data.json',lines=True,nrows=1000)
df_africa.head()

,created_at,id,id_str,text,truncated,entities,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,retweet_count,favorite_count,favorited,retweeted,lang,extended_entities,possibly_sensitive,quoted_status_id,quoted_status_id_str,quoted_status
0,2022-04-22 22:20:18+00:00,1517629396575784961,1517629396575784960,RT @nikitheblogger: Irre: Annalena Baerbock sa...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/android"" ...",NaN,NaN,NaN,...,355,0,False,False,de,NaN,NaN,NaN,NaN,NaN
1,2022-04-22 22:19:16+00:00,1517629134012399616,1517629134012399616,RT @sagt_mit: Merkel schaffte es in 1 Jahr 1 M...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/android"" ...",NaN,NaN,NaN,...,505,0,False,False,de,NaN,NaN,NaN,NaN,NaN
2,2022-04-22 22:17:28+00:00,1517628682659106822,1517628682659106816,RT @Kryptonoun: @WRi007 Pharma in Lebensmittel...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/android"" ...",NaN,NaN,NaN,...,4,0,False,False,de,NaN,NaN,NaN,NaN,NaN
3,2022-04-22 22:17:20+00:00,1517628647892561924,1517628647892561920,RT @WRi007: Die #Deutschen sind ein braves Vol...,False,"{'hashtags': [{'text': 'Deutschen', 'indices':...","<a href=""http://twitter.com/download/android"" ...",NaN,NaN,NaN,...,332,0,False,False,de,NaN,NaN,NaN,NaN,NaN
4,2022-04-22 22:13:15+00:00,1517627621135237127,1517627621135237120,RT @RolandTichy: Baerbock verk√ºndet mal so neb...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/android"" ...",NaN,NaN,NaN,...,386,0,False,False,de,NaN,NaN,NaN,NaN,NaN

In [24]:
pd.DataFrame(df_africa.columns)

                            0
0                  created_at
1                          id
2                      id_str
3                        text
4                   truncated
5                    entities
6                      source
7       in_reply_to_status_id
8   in_reply_to_status_id_str
9         in_reply_to_user_id
10    in_reply_to_user_id_str
11    in_reply_to_screen_name
12                       user
13                        geo
14                coordinates
15                      place
16               contributors
17           retweeted_status
18            is_quote_status
19              retweet_count
20             favorite_count
21                  favorited
22                  retweeted
23                       lang
24          extended_entities
25         possibly_sensitive
26           quoted_status_id
27       quoted_status_id_str
28              quoted_status

In [29]:
df_africa.head(3).T

,0,1,2
created_at,2022-04-22 22:20:18+00:00,2022-04-22 22:19:16+00:00,2022-04-22 22:17:28+00:00
id,1517629396575784961,1517629134012399616,1517628682659106822
id_str,1517629396575784960,1517629134012399616,1517628682659106816
text,RT @nikitheblogger: Irre: Annalena Baerbock sa...,RT @sagt_mit: Merkel schaffte es in 1 Jahr 1 M...,RT @Kryptonoun: @WRi007 Pharma in Lebensmittel...
truncated,False,False,False
entities,"{'hashtags': [], 'symbols': [], 'user_mentions...","{'hashtags': [], 'symbols': [], 'user_mentions...","{'hashtags': [], 'symbols': [], 'user_mentions..."
source,"<a href=""http://twitter.com/download/android"" ...","<a href=""http://twitter.com/download/android"" ...","<a href=""http://twitter.com/download/android"" ..."
in_reply_to_status_id,NaN,NaN,NaN
in_reply_to_status_id_str,NaN,NaN,NaN
in_reply_to_user_id,NaN,NaN,NaN
in_reply_to_user_id_str,NaN,NaN,NaN
in_reply_to_screen_name,None,None,None
user,"{'id': 1487174445248692233, 'id_str': '1487174...","{'id': 1487174445248692233, 'id_str': '1487174...","{'id': 1487174445248692233, 'id_str': '1487174..."
geo,NaN,NaN,NaN
coordinates,NaN,NaN,NaN
place,None,None,None
contributors,NaN,NaN,NaN
retweeted_status,{'created_at': 'Fri Apr 22 14:38:54 +0000 2022...,{'created_at': 'Thu Apr 21 15:44:41 +0000 2022...,{'created_at': 'Thu Apr 21 09:46:16 +0000 2022...
is_quote_status,False,False,False
retweet_count,355,505,4
favorite_count,0,0,0
favorited,False,False,False
retweeted,False,False,False
lang,de,de,de
extended_entities,NaN,NaN,NaN
possibly_sensitive,NaN,NaN,NaN
quoted_status_id,NaN,NaN,NaN
quoted_status_id_str,NaN,NaN,NaN
quoted_status,NaN,NaN,NaN

In [5]:
df_twitter.head()

,created_at,id,id_str,full_text,truncated,display_text_range,entities,metadata,source,in_reply_to_status_id,...,retweet_count,favorite_count,favorited,retweeted,lang,extended_entities,possibly_sensitive,quoted_status_id,quoted_status_id_str,quoted_status
0,2022-08-03 20:19:13+00:00,1554924874166149120,1554924874166149120,#Pelosi airplane landed safely in #Taiwan üáπüáº ...,False,"[0, 222]","{'hashtags': [{'text': 'Pelosi', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,0,False,False,en,NaN,NaN,NaN,NaN,NaN
1,2022-08-02 15:24:42+00:00,1554488368347680771,1554488368347680768,Watch the video of the beginning of the Chines...,False,"[0, 250]","{'hashtags': [{'text': 'Pelosi', 'indices': [1...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""https://mobile.twitter.com"" rel=""nofo...",NaN,...,0,3,False,False,en,"{'media': [{'id': 1554487694776012800, 'id_str...",0.0,NaN,NaN,NaN
2,2022-08-02 15:02:35+00:00,1554482802502127621,1554482802502127616,#Pelosi \n#Taipei \n#taiwan\n#XiJinping \n#Chi...,False,"[0, 71]","{'hashtags': [{'text': 'Pelosi', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,2,False,False,en,"{'media': [{'id': 1554482776140906497, 'id_str...",0.0,NaN,NaN,NaN
3,2022-08-01 13:51:42+00:00,1554102573635932160,1554102573635932160,#HOBIPALOOZA #LaAcademiaExpulsion #WEURO2022 #...,False,"[0, 146]","{'hashtags': [{'text': 'HOBIPALOOZA', 'indices...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,0,False,False,en,"{'media': [{'id': 1554102566010732544, 'id_str...",0.0,NaN,NaN,NaN
4,2022-07-31 20:02:20+00:00,1553833459440910338,1553833459440910336,#Pelosi\n#china\nChina Time ‚úåÔ∏è https://t.co/tE...,False,"[0, 28]","{'hashtags': [{'text': 'Pelosi', 'indices': [0...","{'iso_language_code': 'en', 'result_type': 're...","<a href=""http://twitter.com/download/android"" ...",NaN,...,0,2,False,False,en,"{'media': [{'id': 1553833456853045256, 'id_str...",0.0,NaN,NaN,NaN

In [21]:
pd.set_option('display.max_colwidth',550)
df_twitter['user']

0       {'id': 1183669359396511744, 'id_str': '1183669359396511744', 'name': 'Critical Thinking DZ ÿßŸÑÿ™ŸÅŸÉŸäÿ± ÿßŸÑŸÜŸÇÿØŸä', 'screen_name': 'DzCritical', 'location': 'Alg√©rie', 'description': 'Science, histoire, philosophie, derni√®res nouvelles, M√©dias et des id√©es saines.
ÿπŸÑŸàŸÖ, ÿ™ÿßÿ±ŸäÿÆ, ŸÅŸÑÿ≥ŸÅÿ©ÿå ÿßÿÆÿ®ÿßÿ± ÿßŸÑÿ≥ÿßÿπÿ© Ÿà ÿ£ŸÅŸÉÿßÿ±.', 'url': 'https://t.co/bKmczKcTmV', 'entities': {'url': {'urls': [{'url': 'https://t.co/bKmczKcTmV', 'expanded_url': 'http://criticalthinkingdz.gmail.com', 'display_url': 'criticalthinkingdz.gmail.com', 'indices': [0, 23]}]}, 'description': {'urls...
1       {'id': 746340422994235392, 'id_str': '746340422994235392', 'name': 'News 24/24', 'screen_name': 'toopsat', 'location': '', 'description': '', 'url': 'https://t.co/uMXkNVgcUG', 'entities': {'url': {'urls': [{'url': 'https://t.co/uMXkNVgcUG', 'expanded_url': 'https://www.toopsat.com', 'display_url': 'toopsat.com', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 764, 'friends_count': 144, 'listed_count': 3, 'created_at': 'Fri Jun 24 13:53:18 +0000 2016', 'favourites_count': 2160, 'utc_offset': None, ...
2       {'id': 1138076883399188480, 'id_str': '1138076883399188480', 'name': '‚ô•Ô∏èNassou üá©üáøSupernova Emyüáµüá∏', 'screen_name': 'NassimaLilEmy', 'location': 'Alg√©rie', 'description': 'When you pray for the rain , you got to deal with the mud .', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 64, 'friends_count': 47, 'listed_count': 0, 'created_at': 'Mon Jun 10 13:34:08 +0000 2019', 'favourites_count': 10841, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 22...
3       {'id': 1446461696357371906, 'id_str': '1446461696357371906', 'name': 'DHAYAE BELBOULA', 'screen_name': 'd_dhayae', 'location': 'Chlef                         ', 'description': 'DhaYae', 'url': 'https://t.co/KhVsHCLjI7', 'entities': {'url': {'urls': [{'url': 'https://t.co/KhVsHCLjI7', 'expanded_url': 'https://youtube.com/channel/UCIPzSxvRJQjS_oBJsl8PduQ', 'display_url': 'youtube.com/channel/UCIPzS‚Ä¶', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count': 60, 'friends_count': 463, 'listed_count': 0, 'creat...
4       {'id': 1435461161076596736, 'id_str': '1435461161076596736', 'name': 'ŸÖÿ≠ŸÖÿØ ÿßŸÖŸäŸÜ', 'screen_name': 'Mohamme65404115', 'location': 'Alg√©rie', 'description': '', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 39, 'friends_count': 206, 'listed_count': 0, 'created_at': 'Wed Sep 08 04:33:24 +0000 2021', 'favourites_count': 5947, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': False, 'statuses_count': 1313, 'lang': None, 'contributors_enabled': False, 'is_translator': False, '...
                                                                                                                                                                                                                                                                                        ...
4995    {'id': 1191062780310360070, 'id_str': '1191062780310360070', 'name': 'SKRIMGADGETS', 'screen_name': 'skrimgadgets', 'location': 'Ibadan', 'description': 'We SELL; We BUY; We SWAP, We FIX LAPTOP Computers | Computer Engineer | Quick Response Squad ‚òé / TEXT 08134455771 | Email - contactskrimgadgets@gmail.com', 'url': 'https://t.co/7FSEk6OpLT', 'entities': {'url': {'urls': [{'url': 'https://t.co/7FSEk6OpLT', 'expanded_url': 'https://wa.me/c/2348134455771', 'display_url': 'wa.me/c/2348134455771', 'indices': [0, 23]}]}, 'description': {'urls': [...
4996    {'id': 1237133081452187648, 'id_str': '1237133081452187648', 'name': 'Temitope Ajilaüåª', 'screen_name': 'Temitope_7', 'location': 'Akure, Nigeria ', 'description': 'Tech| Web Design| NFT | e-mail: nelsontemitope5@gmail.com, LinkedIn https://t.co/3RJPCQ27Gh', 'url': 'https://t.co/VLmfQ6uvkU', 'entities': {'url': {'urls': [{'url': 'https://t.co/VLmfQ6uvkU', 'expanded_url': 'https://opensea.io/collection/untitled-collection-270350931', 'display_url': 'opensea.io/collection/unt‚Ä¶', 'indices': [0, 23]}]}, 'description': {'urls': [{'url': 'https://...
4997    {'id': 1198015707277152258, 'id_str': '1198015707277152258', 'name': 'Patson Luxury Homes!!!', 'screen_name': 'MrJayPappy1', 'location': 'Port Harcourt, Nigeria', 'description': 'Port Harcourt Realtor, Business Dev, Interior Deco.. Chelsea FC fan ... Good music stan. trying to grow my 4th account so FB too, 3 suspended', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 2293, 'friends_count': 2390, 'listed_count': 1, 'created_at': 'Fri Nov 22 23:10:17 +0000 2019', 'favourites_count': 4754, 'utc_o...
4998    {'id': 773160289, 'id_str': '773160289', 'name': 'Reconcept', 'screen_name': 'reconceptl', 'location': 'Enugu, Nigeria', 'description': 'Author and blog writer|| Mindset coach Taking you on a journey of creating your desired life and becoming a part of the society.', 'url': 'https://t.co/bKNLeTJMM4', 'entities': {'url': {'urls': [{'url': 'https://t.co/bKNLeTJMM4', 'expanded_url': 'http://medium.com/@reconcept', 'display_url': 'medium.com/@reconcept', 'indices': [0, 23]}]}, 'description': {'urls': []}}, 'protected': False, 'followers_count':...
4999    {'id': 187204088, 'id_str': '187204088', 'name': 'Jedi Skywalker', 'screen_name': 'irosky007', 'location': 'ABUJA', 'description': 'Political Analyst, Promoter of truth and justice. (Tell it as it is).', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 1646, 'friends_count': 602, 'listed_count': 13, 'created_at': 'Sun Sep 05 15:28:00 +0000 2010', 'favourites_count': 362, 'utc_offset': None, 'time_zone': None, 'geo_enabled': True, 'verified': False, 'statuses_count': 37514, 'lang': None, 'contrib...
Name: user, Length: 5000, dtype: object

In [7]:
df_twitter.head(3).T

,0,1,2
created_at,2022-08-03 20:19:13+00:00,2022-08-02 15:24:42+00:00,2022-08-02 15:02:35+00:00
id,1554924874166149120,1554488368347680771,1554482802502127621
id_str,1554924874166149120,1554488368347680768,1554482802502127616
full_text,#Pelosi airplane landed safely in #Taiwan üáπüáº ...,Watch the video of the beginning of the Chines...,#Pelosi \n#Taipei \n#taiwan\n#XiJinping \n#Chi...
truncated,False,False,False
display_text_range,"[0, 222]","[0, 250]","[0, 71]"
entities,"{'hashtags': [{'text': 'Pelosi', 'indices': [0...","{'hashtags': [{'text': 'Pelosi', 'indices': [1...","{'hashtags': [{'text': 'Pelosi', 'indices': [0..."
metadata,"{'iso_language_code': 'en', 'result_type': 're...","{'iso_language_code': 'en', 'result_type': 're...","{'iso_language_code': 'en', 'result_type': 're..."
source,"<a href=""http://twitter.com/download/android"" ...","<a href=""https://mobile.twitter.com"" rel=""nofo...","<a href=""http://twitter.com/download/android"" ..."
in_reply_to_status_id,NaN,NaN,NaN
in_reply_to_status_id_str,NaN,NaN,NaN
in_reply_to_user_id,NaN,NaN,NaN
in_reply_to_user_id_str,NaN,NaN,NaN
in_reply_to_screen_name,None,None,None
user,"{'id': 1183669359396511744, 'id_str': '1183669...","{'id': 746340422994235392, 'id_str': '74634042...","{'id': 1138076883399188480, 'id_str': '1138076..."
geo,NaN,NaN,NaN
coordinates,NaN,NaN,NaN
place,None,None,None
contributors,NaN,NaN,NaN
is_quote_status,False,False,False
retweet_count,0,0,0
favorite_count,0,3,2
favorited,False,False,False
retweeted,False,False,False
lang,en,en,en
extended_entities,NaN,"{'media': [{'id': 1554487694776012800, 'id_str...","{'media': [{'id': 1554482776140906497, 'id_str..."
possibly_sensitive,NaN,0.0,0.0
quoted_status_id,NaN,NaN,NaN
quoted_status_id_str,NaN,NaN,NaN
quoted_status,NaN,NaN,NaN

In [13]:
# Since the number of columns are too many, we won't be able to see the entire info. So we can see half at a time.

half = len(df_twitter.columns) // 2

df_twitter.iloc[:, :half].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   created_at                 1000 non-null   datetime64[ns, UTC]
 1   id                         1000 non-null   int64
 2   id_str                     1000 non-null   int64
 3   full_text                  1000 non-null   object
 4   truncated                  1000 non-null   bool
 5   display_text_range         1000 non-null   object
 6   entities                   1000 non-null   object
 7   metadata                   1000 non-null   object
 8   source                     1000 non-null   object
 9   in_reply_to_status_id      103 non-null    float64
 10  in_reply_to_status_id_str  103 non-null    float64
 11  in_reply_to_user_id        120 non-null    float64
 12  in_reply_to_user_id_str    120 non-null    float64
 13  in_reply_to_screen_name    120 non-null    object
 14  user                       1000 non-null   object
dtypes: bool(1), datetime64[ns, UTC](1), float64(4), int64(2), object(7)
memory usage: 110.5+ KB

In [15]:
df_twitter.iloc[:, half:].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   geo                   0 non-null      float64
 1   coordinates           0 non-null      float64
 2   place                 107 non-null    object
 3   contributors          0 non-null      float64
 4   is_quote_status       1000 non-null   bool
 5   retweet_count         1000 non-null   int64
 6   favorite_count        1000 non-null   int64
 7   favorited             1000 non-null   bool
 8   retweeted             1000 non-null   bool
 9   lang                  1000 non-null   object
 10  extended_entities     631 non-null    object
 11  possibly_sensitive    763 non-null    float64
 12  quoted_status_id      37 non-null     float64
 13  quoted_status_id_str  37 non-null     float64
 14  quoted_status         37 non-null     object
dtypes: bool(3), float64(6), int64(2), object(4)
memory usage: 96.8+ KB

In [23]:
pd.DataFrame(df_twitter.columns)

                            0
0                  created_at
1                          id
2                      id_str
3                   full_text
4                   truncated
5          display_text_range
6                    entities
7                    metadata
8                      source
9       in_reply_to_status_id
10  in_reply_to_status_id_str
11        in_reply_to_user_id
12    in_reply_to_user_id_str
13    in_reply_to_screen_name
14                       user
15                        geo
16                coordinates
17                      place
18               contributors
19            is_quote_status
20              retweet_count
21             favorite_count
22                  favorited
23                  retweeted
24                       lang
25          extended_entities
26         possibly_sensitive
27           quoted_status_id
28       quoted_status_id_str
29              quoted_status

In [19]:
df_twitter['lang'].value_counts()

lang
en    1000
Name: count, dtype: int64